### ISSUE TITLE
Fails with .NET 4.6 - ResponseData explicit layout

### ISSUE THREAD

**Issue by kuiperzone** [demot/RandomOrgJson-RPC#2]
Giving overlapping offset error for ResponseData class on response reception. Removed explicit layout fieldset, so as below, and it seems fine:

        struct ResponseData
        {
            public int[] Integers;
            public string[] Strings;
            public double[] Doubles;
            public Guid[] UUIDs;
            public Usage Usage;
            public string ErrorMessage;
            public JsonObject Result;
            public int ErrorCode;
        }

**Comment by demot** [comment]
The explicit layout attribute is used for memory optimization. You can argue that the footprint of 5 unused pointers is not relevant in most cases. A better approach would be to get rid of the struct, use an object which holds the pointer to the data and cast it in the specific methods.
I will look into it in more detail over the weekend. Thanks for the information!

**Comment by kuiperzone** [comment]
I would bet money that you are really a C or C++ programmer! :)

**Comment by demot** [comment]
Hope you did not - I started with Visual Basic ;)
I wrote some Cpp programs, just to look behind the scences of how many of the more popular compilers are build and to be familiar with some core concepts of programming.

**Comment by demot** [comment]
The response handling got restructured, so no more ResponseData and explicit layouts!
The data is converted when it is needed, so data access optimization is now on the users side.
